import json
import os
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from dotenv import load_dotenv

# Import the retry-enabled client
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from geos_agent.api_client import OpenRouterClient, RetryConfig

load_dotenv()

# extract examples from .rst sphinx doc files


XmlFileBundle = List[Dict[str, str]]


# ---------- Data structures ----------


@dataclass
class ExampleGroundTruth:
    """
    Structured representation of one GEOS documentation example.

    This is what you'll later serialize to JSON and feed into your
    evaluation harness.
    """

    example_id: str  # e.g. "basic/multiphaseFlow"
    title: str  # "Multiphase Flow"
    category: str  # "basic" or "advanced"
    rst_path: str  # relative path from repo root

    # Natural-language text to use as prompt context
    context: str
    objectives: str
    description: str  # optional extra free text
    
    # LLM-generated comprehensive natural language specification
    natural_language_spec: str  # Full spec generated by LLM from RST content
    
    # Full XML content for ground truth comparison
    xml_content: str  # Complete XML file contents
    ground_truth_experiment: str  # Matched directory under data/eval/experiments_gt
    ground_truth_xml_files: List[str]  # XML files read from the matched inputs/ dir

    # Ground truth "code" the agent should recover
    input_files: List[str]  # XML decks and any other required inputs
    aux_files: List[str]  # tables, meshes, helper scripts, etc.
    run_commands: List[str]  # canonical geosx / MPI / python commands
    postprocess_commands: List[str]  # python plotting scripts or similar
    expected_outputs: List[str]  # files or glob patterns

    def to_jsonable(self) -> Dict[str, Any]:
        d = asdict(self)
        # Make sure everything is JSON-serializable
        return d


# ---------- Low-level utilities ----------

SECTION_HEADERS = [
    "Context",
    "Objective",
    "Objectives",
    "Input file",
    "Input files",
    "Running GEOS",
    "Running TriaxialDriver",
    "Running",
    "Inspecting results",
    "Results",
]

FILE_PATH_RE = re.compile(
    r"""
    (?P<path>
        (?:\.\./)*inputFiles/[^\s`]+ |
        src/docs/sphinx/[^\s`]+     |
        GEOSDATA[^\s`]*             |
        [A-Za-z0-9_.\-/]+\.xml      |
        [A-Za-z0-9_.\-/]+\.py       |
        [A-Za-z0-9_.\-/]+\.txt      |
        [A-Za-z0-9_.\-/]+\.vtu      |
        [A-Za-z0-9_.\-/]+\.vtk      |
        [A-Za-z0-9_.\-/]+\.csv      |
        [A-Za-z0-9_.\-/]+\.h5       |
        [A-Za-z0-9_.\-/]+\.xdmf     |
        [A-Za-z0-9_.\-/]+\.xmf
    )
    """,
    re.VERBOSE,
)

RUN_CMD_RE = re.compile(
    r"""
    ^\s*
    (?:
        (?:mpirun|mpiexec)[^\n]*geosx[^\n]* |
        (?:\$\s*)?(?:\S*/)?geosx[^\n]*-i[^\n]* |
        python\s+[^\n]*\.py[^\n]*
    )
    """,
    re.IGNORECASE | re.VERBOSE,
)

# Very loose heuristic: expected outputs are files mentioned
# in a section whose header contains "Inspecting results" or "Results".
OUTPUT_SECTION_HINTS = {"inspecting results", "results"}


def _read_text(path: Path) -> List[str]:
    text = path.read_text(encoding="utf-8")
    return text.splitlines()


def _find_section_indices(lines: List[str]) -> Dict[str, int]:
    """
    Return a map from header name (as in SECTION_HEADERS) to the
    line index where that header appears.

    We treat a line that matches the header *exactly* as the header.
    """
    indices: Dict[str, int] = {}
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped in SECTION_HEADERS and stripped not in indices:
            indices[stripped] = i
    return indices


def _slice_section(lines: List[str], start_idx: int, end_idx: Optional[int]) -> str:
    if end_idx is None:
        end = len(lines)
    else:
        end = end_idx
    # Skip the header line itself
    body = lines[start_idx + 1 : end]
    return "\n".join(body).strip()


def _extract_first_matching_section(
    lines: List[str],
    header_map: Dict[str, int],
    names: List[str],
    next_section_start: int | None,
) -> str:
    """
    Return the concatenated body of the first section found among `names`.
    """
    for name in names:
        if name in header_map:
            start_idx = header_map[name]
            end_idx: Optional[int] = None
            if next_section_start is not None and next_section_start > start_idx:
                end_idx = next_section_start
            return _slice_section(lines, start_idx, end_idx)
    return ""


def _extract_all_paths(text: str) -> List[str]:
    paths = []
    for m in FILE_PATH_RE.finditer(text):
        paths.append(m.group("path"))
    # Deduplicate while preserving order
    seen = set()
    unique = []
    for p in paths:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    return unique


def _extract_data_paths(xml_content: str) -> List[str]:
    """
    Extract paths relative to GEOSDATA or GEOS directories from XML content.
    Returns a unique list of relative paths.
    """
    if not xml_content:
        return []

    # Look for paths like .../GEOSDATA/path/to/file or .../GEOS/path/to/file
    # Capture the "GEOSDATA/..." or "GEOS/..." part (group 2)
    # The regex matches:
    # 1. Start quote (['"])
    # 2. Any chars not the quote
    # 3. (GEOSDATA|GEOS)/... and captures it
    # 4. End quote (backreference)
    pattern = r'([\'"])[^\'"]*((?:GEOSDATA|GEOS)/[^\'"]+)\1'
    
    paths = []
    for match in re.finditer(pattern, xml_content):
        paths.append(match.group(2))
    
    # Deduplicate and sort
    return sorted(list(set(paths)))


def _clean_experiment_name(value: str) -> str:
    """Match the experiment folder naming used by scripts/eval/generate_experiments.py."""
    return re.sub(r"[^a-zA-Z0-9]", "", value)


def _candidate_experiment_names(title: str, example_name: str) -> List[str]:
    candidates = []

    cleaned_title = _clean_experiment_name(title)
    if cleaned_title:
        candidates.append(cleaned_title)

    if example_name and example_name != "unknown":
        candidates.extend(
            [
                example_name,
                f"Example{example_name[:1].upper()}{example_name[1:]}",
                f"Tutorial{example_name[:1].upper()}{example_name[1:]}",
                f"AdvancedExample{example_name[:1].upper()}{example_name[1:]}",
            ]
        )

    return list(dict.fromkeys(candidates))


def _find_ground_truth_experiment_dir(
    ground_truth_dir: Optional[Path],
    title: str,
    example_name: str,
) -> Optional[Path]:
    if ground_truth_dir is None or not ground_truth_dir.is_dir():
        return None

    for candidate in _candidate_experiment_names(title, example_name):
        direct_match = ground_truth_dir / candidate
        if direct_match.is_dir():
            return direct_match

    casefolded = {
        child.name.casefold(): child
        for child in ground_truth_dir.iterdir()
        if child.is_dir()
    }
    for candidate in _candidate_experiment_names(title, example_name):
        match = casefolded.get(candidate.casefold())
        if match is not None:
            return match

    return None


def _read_ground_truth_xml_files(
    experiment_dir: Optional[Path],
) -> XmlFileBundle:
    if experiment_dir is None:
        return []

    inputs_dir = experiment_dir / "inputs"
    if not inputs_dir.is_dir():
        return []

    xml_files: XmlFileBundle = []
    for xml_path in sorted(inputs_dir.rglob("*.xml")):
        try:
            xml_files.append(
                {
                    "path": xml_path.relative_to(experiment_dir).as_posix(),
                    "content": xml_path.read_text(encoding="utf-8"),
                }
            )
        except UnicodeDecodeError:
            xml_files.append(
                {
                    "path": xml_path.relative_to(experiment_dir).as_posix(),
                    "content": xml_path.read_text(encoding="latin-1"),
                }
            )

    return xml_files


def _format_xml_bundle(xml_files: XmlFileBundle) -> str:
    sections = []
    for xml_file in xml_files:
        sections.append(
            f"--- {xml_file['path']} ---\n"
            "```xml\n"
            f"{xml_file['content']}\n"
            "```"
        )
    return "\n\n".join(sections)


def _combine_xml_content(xml_files: XmlFileBundle) -> str:
    if not xml_files:
        return ""
    return "\n\n".join(
        f"<!-- BEGIN {xml_file['path']} -->\n"
        f"{xml_file['content']}\n"
        f"<!-- END {xml_file['path']} -->"
        for xml_file in xml_files
    )


def _extract_run_commands(text: str) -> List[str]:
    cmds = []
    for line in text.splitlines():
        m = RUN_CMD_RE.match(line)
        if m:
            cmd = line.strip()
            if cmd.startswith("$"):
                cmd = cmd.lstrip("$").strip()
            if cmd and cmd not in cmds:
                cmds.append(cmd)
    return cmds

# ---------- LLM-based spec generation ----------


def generate_spec_with_llm(
    rst_content: str,
    example_id: str,
    data_paths: Optional[List[str]] = None,
    ground_truth_xml_files: Optional[XmlFileBundle] = None,
) -> str:
    """
    Use OpenRouter to generate a comprehensive natural language specification
    from the full RST documentation and, when available, the exact ground-truth
    XML files for the experiment.
    """
    # Use retry-enabled client with reasonable defaults for batch processing
    retry_config = RetryConfig(
        max_retries=5,  # More retries for batch processing
        retry_delay=2.0,  # Slightly longer initial delay
        retry_backoff=2.0,
    )
    client = OpenRouterClient(
        api_key=os.environ.get("OPENROUTER_API_KEY"),
        retry_config=retry_config,
    )

    prompt = f"""You are simulating a user's natural-language geophysics modeling request for an evaluation task. Another AI agent will receive only your final request and must recreate the same hidden reference inputs.

The simulated user understands the geophysics domain and the physical modeling goal, but they do not know anything about GEOS. They do not know GEOS exists, do not know GEOS XML structure, do not know GEOS-specific object names, and do not know GEOS implementation concepts. Write as that user: describe what they want to simulate and what physical or numerical constraints matter, using only domain language.

Use the RST documentation as the explanatory source and the ground-truth XML files, when provided, as private reference material for exact numerical values, schedules, material parameters, mesh details, boundary/initial conditions, outputs, and file organization. Do not reveal that the reference material is XML or GEOS-specific.

Write the final request in natural prose, as if a geoscientist or simulation engineer is asking someone else to build the simulation for them without specifying the software implementation. Organize it by the physical modeling story and what the user needs to simulate, not by the order, hierarchy, or grouping of the private reference files. A good response usually starts with the physical problem and goal, then naturally introduces the domain geometry, materials, operating conditions, constraints, time horizon, numerical fidelity needs, and outputs. Include exact numerical values and units wherever the sources provide them.

Important style constraints:
- Do not include XML code.
- Do not include GEOS syntax.
- Do not mention GEOS.
- Do not mention XML.
- Do not mention XML tag names, XML attribute names, XML object paths, or block-by-block instructions.
- Do not mirror the ground-truth XML ordering or write a section-by-section implementation checklist.
- Do not use headings that correspond to XML block order, such as solver, mesh, events, numerical methods, element regions, constitutive, field specifications, outputs, and tasks.
- Do not say "set this parameter on this solver" or "create a Solvers/Mesh/Events block"; instead describe the scientific or simulation requirement that the model must satisfy.
- Avoid GEOS-specific names unless they are also standard geophysics or numerical-method terminology. Prefer phrases like "poroelastic consolidation", "single-phase flow", "Drucker-Prager plasticity", "finite-volume flow discretization", or "hexahedral mesh" over GEOS implementation names.
- If the reference uses multiple input files, describe the conceptual split only if it is natural for a domain user, for example "use a reusable base case and a benchmark case"; do not mention file formats, filenames, include mechanics, or software configuration mechanics unless a non-software external data file is truly part of the physical problem.
- The output should be complete and self-contained enough for a capable simulation agent to recreate the hidden reference inputs, but it should read like a natural modeling request with constraints rather than an implementation walkthrough.
- The final line of your response must be exactly: XML files to create: <comma-separated list of the exact XML filenames from the private reference files, without directory paths>. This is the only place where you may mention XML.

Example ID: {example_id}

RST Documentation:
{rst_content}
"""

    if ground_truth_xml_files:
        prompt += f"""

Ground-Truth XML Files (private reference context; do not quote or reproduce as XML in your response):
{_format_xml_bundle(ground_truth_xml_files)}
"""

    if data_paths:
        prompt += f"""

Relevant Data Files (must be referenced by these exact paths):
"""
        for p in data_paths:
            prompt += f"- {p}\n"

    prompt += "\nGenerate the natural language specification:"

    def _make_call():
        response = client.chat.completions.create(
            model="google/gemini-3.1-pro-preview",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=100000,
            extra_body={"reasoning": {"enabled": True}},
        )
        return response.choices[0].message.content or ""

    return client.with_retry(_make_call, f"LLM spec generation for {example_id}")


# ---------- Example-level parsing ----------


def parse_example_rst(
    rst_path: Path,
    category: str,
    repo_root: Path,
    ground_truth_dir: Optional[Path] = None,
) -> ExampleGroundTruth:
    """
    Parse a single Example.rst-like file into an ExampleGroundTruth object.

    This uses simple heuristics tailored to the GEOS docs; you can
    refine the regexes once you've inspected more examples.
    """
    lines = _read_text(rst_path)
    header_map = _find_section_indices(lines)

    # Title: first non-empty line
    title = ""
    for line in lines:
        if line.strip():
            title = line.strip()
            break

    # To find section boundaries, we sort headers by line index.
    header_items = sorted(header_map.items(), key=lambda kv: kv[1])
    header_starts = [idx for _, idx in header_items]

    def next_header_after(idx: int) -> Optional[int]:
        for h in header_starts:
            if h > idx:
                return h
        return None

    # Context / Objectives section bodies
    context = ""
    if any(h in header_map for h in ("Context",)):
        idx = min(header_map[h] for h in ("Context",) if h in header_map)
        next_idx = next_header_after(idx)
        context = _slice_section(lines, idx, next_idx)

    objectives = ""
    if any(h in header_map for h in ("Objective", "Objectives")):
        idx = min(header_map[h] for h in ("Objective", "Objectives") if h in header_map)
        next_idx = next_header_after(idx)
        objectives = _slice_section(lines, idx, next_idx)

    # For description, just grab a bit more of the file (optional)
    description = ""
    if "Context" in header_map:
        start = header_map["Context"]
        # up to e.g. "Input file" if present
        end = header_map.get("Input file", header_map.get("Input files"))
        description = _slice_section(lines, start, end)

    full_text = "\n".join(lines)

    # Input files: prioritize paths near the "Input file(s)" section if present
    input_files: List[str] = []
    aux_files: List[str] = []

    if "Input file" in header_map or "Input files" in header_map:
        header_name = "Input file" if "Input file" in header_map else "Input files"
        idx = header_map[header_name]
        next_idx = next_header_after(idx)
        input_section_text = _slice_section(lines, idx, next_idx)
        input_paths = _extract_all_paths(input_section_text)
        input_files.extend(input_paths)

    # If we didn't find any, fall back to scanning entire file
    if not input_files:
        input_files = _extract_all_paths(full_text)

    # Run commands: look for commands in "Running..." / "Inspecting results" first
    run_commands: List[str] = []
    postprocess_commands: List[str] = []

    for hname in header_map:
        lower = hname.lower()
        idx = header_map[hname]
        next_idx = next_header_after(idx)
        sec_text = _slice_section(lines, idx, next_idx)

        cmds = _extract_run_commands(sec_text)
        if "running" in lower:
            for c in cmds:
                if "geosx" in c and c not in run_commands:
                    run_commands.append(c)
                elif c not in postprocess_commands:
                    postprocess_commands.append(c)
        elif "inspect" in lower or "results" in lower:
            for c in cmds:
                if "python" in c and c not in postprocess_commands:
                    postprocess_commands.append(c)

    # Fallback: scan whole file for run commands
    if not run_commands and not postprocess_commands:
        cmds = _extract_run_commands(full_text)
        for c in cmds:
            if "geosx" in c:
                run_commands.append(c)
            else:
                postprocess_commands.append(c)

    # Expected outputs: from "Inspecting results" / "Results" sections
    expected_outputs: List[str] = []
    for hname, idx in header_map.items():
        if hname.lower() in OUTPUT_SECTION_HINTS:
            next_idx = next_header_after(idx)
            sec_text = _slice_section(lines, idx, next_idx)
            paths = _extract_all_paths(sec_text)
            for p in paths:
                if p not in expected_outputs:
                    expected_outputs.append(p)

    # Aux files: everything that isn't clearly a primary input deck
    # (This is a heuristic; you can refine it later.)
    primary_ext = {".xml"}
    for p in _extract_all_paths(full_text):
        suffix = Path(p).suffix
        if (
            suffix not in primary_ext
            and p not in input_files
            and p not in expected_outputs
        ):
            aux_files.append(p)
    # Dedup
    aux_files = list(dict.fromkeys(aux_files))

    # Example ID: e.g. "basic/multiphaseFlow"
    # Use path naming convention:
    #   src/docs/sphinx/basicExamples/<name>/Example.rst
    rel = rst_path.relative_to(repo_root).as_posix()
    parts = rst_path.parts
    # ... basicExamples/<name>/Example.rst
    example_name = "unknown"
    if "basicExamples" in parts:
        idx = parts.index("basicExamples")
        if idx + 1 < len(parts):
            example_name = parts[idx + 1]
    elif "advancedExamples" in parts:
        idx = parts.index("advancedExamples")
        if idx + 1 < len(parts):
            example_name = parts[idx + 1]

    example_id = f"{category}/{example_name}"

    gt_experiment_dir = _find_ground_truth_experiment_dir(
        ground_truth_dir,
        title,
        example_name,
    )
    ground_truth_xml_files = _read_ground_truth_xml_files(gt_experiment_dir)
    
    # Read the full XML content from the matched eval ground truth when
    # available. Fall back to the first XML referenced by the RST docs.
    xml_content = ""
    if ground_truth_xml_files:
        xml_content = _combine_xml_content(ground_truth_xml_files)
    elif input_files:
        # Find the first .xml file and resolve it relative to repo_root
        for input_path in input_files:
            if input_path.endswith(".xml"):
                # Handle relative paths like ../../../inputFiles/...
                clean_path = re.sub(r"^(\.\./)+", "", input_path)
                xml_full_path = repo_root / clean_path
                if xml_full_path.exists():
                    try:
                        xml_content = xml_full_path.read_text(encoding="utf-8")
                        break
                    except Exception:
                        pass
    
    # Generate natural language spec using LLM
    print(f"  Generating LLM spec for {example_id}...")
    if gt_experiment_dir is not None:
        print(
            f"    using ground truth: {gt_experiment_dir.name} "
            f"({len(ground_truth_xml_files)} XML files)"
        )
    elif ground_truth_dir is not None:
        print("    [warn] no matching ground truth directory found")
    
    # Extract data paths from XML content if available
    data_paths = _extract_data_paths(xml_content)
    
    try:
        natural_language_spec = generate_spec_with_llm(
            full_text,
            example_id,
            data_paths,
            ground_truth_xml_files,
        )
    except Exception as e:
        print(f"  [warn] LLM call failed: {e}")
        natural_language_spec = ""

    return ExampleGroundTruth(
        example_id=example_id,
        title=title,
        category=category,
        rst_path=rel,
        context=context,
        objectives=objectives,
        description=description,
        natural_language_spec=natural_language_spec,
        xml_content=xml_content,
        ground_truth_experiment=gt_experiment_dir.name if gt_experiment_dir else "",
        ground_truth_xml_files=[xml_file["path"] for xml_file in ground_truth_xml_files],
        input_files=input_files,
        aux_files=aux_files,
        run_commands=run_commands,
        postprocess_commands=postprocess_commands,
        expected_outputs=expected_outputs,
    )


# ---------- Top-level API ----------


def iter_example_rst_paths(
    repo_root: Path,
) -> Iterable[tuple[Path, str]]:
    """
    Yield (rst_path, category) for all Example.rst files under
    basicExamples and advancedExamples.
    """
    basic_root = repo_root / "src" / "docs" / "sphinx" / "basicExamples"
    adv_root = repo_root / "src" / "docs" / "sphinx" / "advancedExamples"

    if basic_root.is_dir():
        for path in basic_root.rglob("Example.rst"):
            yield path, "basic"

    if adv_root.is_dir():
        for path in adv_root.rglob("Example.rst"):
            yield path, "advanced"


def iter_mined_examples(
    repo_root: Path,
    ground_truth_dir: Optional[Path] = None,
    num_workers: int = 1,
) -> Iterable[ExampleGroundTruth]:
    """
    Generator that parses all GEOS example docs into structured ground truth.
    Yields one example at a time.
    """
    example_paths = list(iter_example_rst_paths(repo_root))
    if num_workers <= 1:
        for rst_path, category in example_paths:
            try:
                ex = parse_example_rst(
                    rst_path,
                    category=category,
                    repo_root=repo_root,
                    ground_truth_dir=ground_truth_dir,
                )
                yield ex
            except Exception as e:
                # You can decide whether to raise or just log a warning.
                # For now, we just print and skip.
                print(f"[warn] Failed to parse {rst_path}: {e}")
        return

    print(f"Using {num_workers} workers for LLM spec generation")
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        future_to_rst = {
            executor.submit(
                parse_example_rst,
                rst_path,
                category=category,
                repo_root=repo_root,
                ground_truth_dir=ground_truth_dir,
            ): rst_path
            for rst_path, category in example_paths
        }

        for future in as_completed(future_to_rst):
            rst_path = future_to_rst[future]
            try:
                yield future.result()
            except Exception as e:
                print(f"[warn] Failed to parse {rst_path}: {e}")


def dump_examples_to_jsonl(
    repo_root: Path,
    out_path: Path,
    ground_truth_dir: Optional[Path] = None,
    num_workers: int = 1,
) -> None:
    """
    Create a JSONL file with all mined examples (one JSON object per line).
    Writes incrementally to disk after each example is processed.
    """
    import json
    
    # Ensure output directory exists
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"Writing results to: {out_path}")
    count = 0
    
    # Open with line buffering (buffering=1) so it flushes on newlines
    with open(out_path, "w", encoding="utf-8", buffering=1) as f:
        for ex in iter_mined_examples(repo_root, ground_truth_dir, num_workers):
            f.write(json.dumps(ex.to_jsonable(), ensure_ascii=False) + "\n")
            f.flush()  # Extra safety explicit flush
            count += 1
            print(f"  > Wrote example {count}: {ex.example_id}")
    
    print(f"\n=== Mining Complete ===")
    print(f"Processed: {count} examples")
    print(f"Output: {out_path}")


def _experiment_folder_name(ex: ExampleGroundTruth) -> str:
    if ex.ground_truth_experiment:
        return ex.ground_truth_experiment

    cleaned_title = _clean_experiment_name(ex.title)
    if cleaned_title:
        return cleaned_title

    return _clean_experiment_name(ex.example_id)


def dump_examples_to_experiment_dirs(
    repo_root: Path,
    experiments_out_dir: Path,
    ground_truth_dir: Optional[Path] = None,
    num_workers: int = 1,
) -> None:
    """
    Create an eval experiment directory for each mined example.

    Each experiment directory contains:
      - instructions.txt with the generated natural-language spec
      - inputs/ for the agent's generated XML files
      - outputs/ for run artifacts
    """
    experiments_out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Writing experiment directories to: {experiments_out_dir}")
    count = 0

    for ex in iter_mined_examples(repo_root, ground_truth_dir, num_workers):
        folder_name = _experiment_folder_name(ex)
        if not folder_name:
            print(f"  [warn] Skipping {ex.example_id}: could not derive folder name")
            continue

        exp_dir = experiments_out_dir / folder_name
        exp_dir.mkdir(parents=True, exist_ok=True)
        (exp_dir / "inputs").mkdir(exist_ok=True)
        (exp_dir / "outputs").mkdir(exist_ok=True)
        (exp_dir / "instructions.txt").write_text(
            ex.natural_language_spec,
            encoding="utf-8",
        )

        count += 1
        print(f"  > Wrote experiment {count}: {folder_name}")

    print(f"\n=== Mining Complete ===")
    print(f"Processed: {count} examples")
    print(f"Output: {experiments_out_dir}")


# Project paths for default CLI usage
PROJECT_ROOT = Path(__file__).resolve().parents[1]


# If you want a small CLI:
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Mine GEOS documentation examples into JSONL ground truth for evaluation."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=PROJECT_ROOT / "data" / "GEOS",
        help="Path to the GEOS repo root (containing src/docs/sphinx).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=PROJECT_ROOT / "data" / "eval" / "example_pairs.jsonl",
        help="Output JSONL path. Ignored when --experiments-out-dir is set.",
    )
    parser.add_argument(
        "--experiments-out-dir",
        type=Path,
        default=None,
        help=(
            "Write experiment folders here instead of JSONL. Each folder gets "
            "instructions.txt plus empty inputs/ and outputs/ directories."
        ),
    )
    parser.add_argument(
        "--ground-truth-dir",
        type=Path,
        default=PROJECT_ROOT / "data" / "eval" / "experiments_gt",
        help=(
            "Directory containing per-experiment ground truth folders with "
            "inputs/*.xml files. Use an empty/nonexistent path to fall back "
            "to XML files referenced in the RST docs only."
        ),
    )
    parser.add_argument(
        "--num-workers",
        type=int,
        default=1,
        help="Number of parallel LLM calls to run while mining examples. Default: 1.",
    )
    args = parser.parse_args()
    if args.num_workers < 1:
        parser.error("--num-workers must be >= 1")

    print("=== Mining GEOS Examples for Evaluation ===\n")
    if args.experiments_out_dir is not None:
        dump_examples_to_experiment_dirs(
            args.repo_root,
            args.experiments_out_dir,
            args.ground_truth_dir,
            args.num_workers,
        )
    else:
        dump_examples_to_jsonl(
            args.repo_root,
            args.out,
            args.ground_truth_dir,
            args.num_workers,
        )
